# 'Prettier' (formatter) was approved by the teacher.
# This formatter 'only' makes the code prettier. Does not affect code itself.

tabWidth: 4
useTabs: True
printWidth: 100

plugins:
    - "@awmottaz/prettier-plugin-void-html"
    # This plugin removes trailing slashes from prettier. Again, does not affect code itself.
